# Generated by Django 5.0.3 on 2024-05-27 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=1)),
                ("Commentid", models.IntegerField(default=1)),
                ("topic_id", models.IntegerField(default=1)),
                ("comment_content", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("stars", models.IntegerField(default=0)),
                (
                    "username",
                    models.CharField(blank=True, default="user", max_length=50),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/images/user-icon.png",
                        upload_to="comment/images",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="user", max_length=100)),
                ("user_id", models.IntegerField(default=1)),
                ("message", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("to", models.CharField(default="", max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default="/static/images/user-icon.png",
                        upload_to="profiles/images",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                            (29, 29),
                            (30, 30),
                            (31, 31),
                        ],
                        default=1,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        default=1,
                    ),
                ),
                ("year", models.IntegerField(default=2010)),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=11, null=True),
                ),
                (
                    "defaultName",
                    models.CharField(blank=True, default="User", max_length=30),
                ),
                (
                    "image",
                    models.ImageField(
                        default="/static/images/user-icon.png",
                        upload_to="profiles/images",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="example@gmail.com", max_length=254
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        default="Nam",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
