# Generated by Django 5.0.3 on 2024-05-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_comment_notification_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product/images")),
                ("title", models.CharField(default="", max_length=150)),
                ("price", models.IntegerField(default=1)),
                (
                    "color",
                    models.CharField(
                        choices=[("Xám", "Xám"), ("Xanh", "Xanh"), ("Đen", "Đen")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        choices=[
                            ("Đà nẵng", "Đà nẵng"),
                            ("Hà nội", "Hà nội"),
                            ("TP HCM", "TP HCM"),
                            ("Quảng ngãi", "Quảng ngãi"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("stars", models.IntegerField(default=1)),
                ("evaluateCount", models.IntegerField(default=0)),
                ("information", models.JSONField(default={})),
            ],
        ),
    ]
