# Generated by Django 5.0.3 on 2024-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="information",
            field=models.JSONField(default=""),
        ),
    ]
