# Generated by Django 5.0.3 on 2024-05-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_product_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="information",
            field=models.JSONField(null=True),
        ),
    ]
