# Generated by Django 5.0.3 on 2024-06-01 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_product_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=150)),
                ("user_id", models.IntegerField(default=1)),
                (
                    "username",
                    models.CharField(blank=True, default="user", max_length=50),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/images/user-icon.png",
                        upload_to="comment/images",
                    ),
                ),
                ("topic_id", models.IntegerField(default=1)),
                ("commentChild_id", models.IntegerField(default=1)),
                ("responder", models.CharField(max_length=150)),
                ("comment_content", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("like", models.IntegerField(default=0)),
                ("dislike", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="stars",
            new_name="dislike",
        ),
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
