# Generated by Django 5.0.3 on 2024-06-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_commentchild_rename_stars_comment_dislike_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="topic_id",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="commentchild",
            old_name="topic_id",
            new_name="product_id",
        ),
    ]
