# Generated by Django 5.0.3 on 2024-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_topic_id_comment_product_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product/images")),
                ("product_id", models.IntegerField(default=1)),
                ("user_id", models.IntegerField(default=1)),
                ("price", models.IntegerField(default=1)),
                ("quality", models.IntegerField(default=1)),
            ],
        ),
    ]
