# Generated by Django 5.0.3 on 2024-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_cart_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="title",
            field=models.CharField(default="", max_length=150),
        ),
    ]
