# Generated by Django 5.0.3 on 2024-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="order_desc",
            field=models.CharField(default="chuyển tiền", max_length=150),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.IntegerField(default=1),
        ),
    ]
